name: learning-engine-prod

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8765:8765"
    volumes:
      - ./backend/data:/app/data

  frontend:
    build:
      context: ./webapp
      target: prod
    ports:
      - "8080:80"
    depends_on:
      - backend
